version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    restart: unless-stopped

  admin:
    build:
      context: ./admin
    container_name: admin
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
    restart: unless-stopped