name: Test Project

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install, Test and Build - Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm test
          npm run build

      - name: Install, Test and Build - Admin
        working-directory: ./admin
        run: |
          npm ci
          npm test
          npm run build

      - name: Install and Test - Backend
        working-directory: ./backend
        run: |
          npm ci
          npm test
