name: Test_Project

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Print directory structure
        run: |
          ls -R ./food_delivery-main

      - name: Install, Test and Build - Frontend
        working-directory: ./food_delivery-main/frontend
        run: |
          ls -alh   # List files to ensure package-lock.json exists
          npm ci
          npm test
          npm run build

      - name: Install, Test and Build - Admin
        working-directory: ./food_delivery-main/admin
        run: |
          ls -alh   # List files to ensure package-lock.json exists
          npm ci
          npm test
          npm run build

      - name: Install and Test - Backend
        working-directory: ./food_delivery-main/backend
        run: |
          ls -alh   # List files to ensure package-lock.json exists
          npm ci
          npm test
