name: Test Project

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install and Build - Frontend
        working-directory: ./food_delivery-main/frontend
        run: |
          npm ci
          npm run build

      - name: Install - Backend
        working-directory: ./food_delivery-main/backend
        run: |
          npm ci
          npm test

      - name: Install and Build - Admin
        working-directory: ./food_delivery-main/admin
        run: |
          npm ci
          npm run build
